FROM node:14-alpine AS builder
WORKDIR /app
COPY frontend/package*.json .
RUN npm install --only=prod

COPY frontend ./

RUN npm run build

FROM nginx:alpine
HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost/

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]